### ISSUE TITLE
Test code generation?

### ISSUE THREAD

**Issue by olale** [GraphWalker/graphwalker-project#10]
Hi!

In the previous version of GraphWalker, there were command line options for generating stubs for the tests. Where are those options now?

**Comment by KristianKarl** [comment]
The all-purpose stub generator is still left to do.

For java though, it has been replaced by the Interface generator. The generator requires that the models are put into the folder:
~~~
src/main/resources
~~~

To generate the interfaces:
~~~
mvn graphwalker:generate-sources
~~~
It is also run (automatically) when running
~~~
mvn graphwalker:test
~~~
or
~~~
mvn graphwalker:watch
~~~
The last command is a convenience command, that if left running, it will update the interface whenever the models are changed.

**Comment by KristianKarl** [comment]
Added task to Trello
https://trello.com/c/eXkNSuz5/78-all-purpose-source-code-generator

**Comment by olale** [comment]
Thanks! I assume that the models are added after the interfaces that they must implement have been generated?

**Comment by KristianKarl** [comment]
With models, we mean the .graphml files. An interface is a representation of the model - a Java Interface.
I believe that what you refer to, is the implementation of an interface. And yes, they are added afterwards by you.
