### ISSUE TITLE
Before element annotation works wrong

### ISSUE THREAD

**Issue by nbdnnm** [GraphWalker/graphwalker-project#101]
In the project on the screenshot I try to implement before element logic, but graphwalker triggers it after element and ever after AfterElement annotation logic

![beforeelement annotation issue](https://cloud.githubusercontent.com/assets/22072588/20428275/6d967ba8-ad88-11e6-9447-6961b694d6bf.png)

**Comment by nilols** [comment]
The implementation of executing `@BeforeElement` and `@AfterElement` should use the `Observer`, the current implementation executes before and after the method if a context exist, therefore the first `@BeforeElement` is not executed. Using the `Observer` will also ensure that it's synchronised with the context, which obviously it is not.

**Comment by nilols** [comment]
Fixed in latest master
