### ISSUE TITLE
Error on requirement_coverage stop condition

### ISSUE THREAD

**Issue by nbdnnm** [GraphWalker/graphwalker-project#102]
Please have a look on attachment
Don't understand what the problem

![image](https://cloud.githubusercontent.com/assets/22072588/20458998/a123a7c6-aeb3-11e6-8676-3aae0229bad2.png)

[ABCD.zip](https://github.com/GraphWalker/graphwalker-project/files/601769/ABCD.zip)

**Comment by KristianKarl** [comment]
That looks like a bug. I'l look at it.

**Comment by nbdnnm** [comment]
fixed in https://github.com/GraphWalker/graphwalker-project/pull/120
