### ISSUE TITLE
Error on reached_shared_state stop condition

### ISSUE THREAD

**Issue by nbdnnm** [GraphWalker/graphwalker-project#103]
During discussion with Kristian and Nils was clarified that in GW exist not documented stop condition reached shared state https://github.com/GraphWalker/graphwalker-project/blob/master/graphwalker-core/src/main/java/org/graphwalker/core/condition/ReachedSharedState.java

Supposed it would looks like on the screenshot, but it doesn't work
![image](https://cloud.githubusercontent.com/assets/22072588/20459029/cd10813c-aeb4-11e6-88d0-b647271d3565.png)

[ABCD.zip](https://github.com/GraphWalker/graphwalker-project/files/601775/ABCD.zip)

**Comment by KristianKarl** [comment]
So, the question if should implement it?
I guess reading @nilols comment in the referred thread, we should.

So I convert this issue to a task.
