### ISSUE TITLE
Multiple shared vertex

### ISSUE THREAD

**Issue by nbdnnm** [GraphWalker/graphwalker-project#106]
Hello,
At work I met with a case when one model may be ended with sharing with another multiple models.
For example I have a single page, on this page placed checkboxes, folder structure, dropdown and search.
I define them as separate 4 models, and would like to test them not only separately, but combined, to see do they impact each other correctly or not.

So, from checkboxes model I may jump in folder or dropdown or search models.
And I may jump from any model on any another as well.

I understand how to make it now, just to add in each model 3 verteces with keyword SHARED and a name of a target model.

But I would like to propose an improvement in GW.

What about multi-sharing vertex where would be able to list a number of links on models?
As far as I know now when GW see a shared keyword, it makes a virtual edge to another model.
In this case GW may create few virtual edges.

![image](https://cloud.githubusercontent.com/assets/22072588/20540033/aabd7b22-b0f7-11e6-9cfa-3979556d9016.png)

**Comment by KristianKarl** [comment]
Interesting. But could not the same already be achieved today? (Not using multiple shared names though) 
Could you give me a use case, where different names for the same shared vertices would be used? 
In your example models, it's not obvious to me why all the shared vertices could have the shared name Z.

**Comment by nbdnnm** [comment]
Yes, it is the same what would be achieved today.
If I want to connect one model to few another, I have to create a shared vertex for each of this model in the first model.
My idea to have a one vertex which aggregate all links on another models.
It would be easier in case of 5-10 linked with each other models

**Comment by nbdnnm** [comment]
I have tried to visualize it
It how is now
![image](https://cloud.githubusercontent.com/assets/22072588/20543644/e580b2e2-b106-11e6-9c47-4ad2e5b307d6.png)
![image](https://cloud.githubusercontent.com/assets/22072588/20543671/03d55644-b107-11e6-8ae7-774480200812.png)

And that is what I propose
![image](https://cloud.githubusercontent.com/assets/22072588/20543803/8b5ae9ee-b107-11e6-97f6-ec863443d96f.png)
![image](https://cloud.githubusercontent.com/assets/22072588/20543954/1b40ced4-b108-11e6-969d-20453ac02f3b.png)

**Comment by KristianKarl** [comment]
Yeah, that makes sense.
Thank you for the clarification!

**Comment by nilols** [comment]
It's a bigger change that you would think, multiple modules need to be changed, but I also think that this change would be good, simplify for the user and also ensure that we handle the model in an intermediate step, in my mind GW would see this combined shared state as multiple in/out edges which would give us the possibility to also solve the street sweeper problem where some edges needs to be traversed multiple times

**Comment by nbdnnm** [comment]
I didn't think that it is easy, and of course don't ask to prioritize it
Let's say that everything what can be done in another way, without improvements, now, has less priority
would be resonable
