### ISSUE TITLE
how to generate the graph

### ISSUE THREAD

**Issue by saikrishna321** [GraphWalker/graphwalker-project#110]
i was able to run the sample appium tests, but where is graphwalker report located?

**Comment by KristianKarl** [comment]
There is no graphwalker report.

For the appium example, the output on the console is what is what you get.

However, you can of course use any reporting frameworks that suites your own development. The test results/reporting are an implementation detail that you need to do yourself. It's very much connected to whatever tools and frameworks you would be using for your automation.

/Best Kristian

PS: General question should be asked here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/graphwalker-3
