### ISSUE TITLE
How do random and quick random actually works?

### ISSUE THREAD

**Issue by nbdnnm** [GraphWalker/graphwalker-project#112]
Hello,
I have found an interesting case:
I try to execute a login into an app few times 
In the model it is 5, but in reality it is array of data inside a test framework, some kind of data driven

If I cover the model with a random generator, I see that it works only inside the login-logout cycle.
On the screen you may see around 15 000 iterations, I don't believe that all this times really randomly was chosen LogOut edge
![image](https://cloud.githubusercontent.com/assets/22072588/20860179/3a11015e-b972-11e6-86fb-943e372a9908.png)

If I execute a quick_random generator I receive the exact number of iterations which needed for choosing of GoToAnotherTests edge. 
(I was trying to repeat, it gives me the same result, 5 login-logout and then GoToAnotherTests)
![image](https://cloud.githubusercontent.com/assets/22072588/20860204/e8a03f6e-b972-11e6-832b-bae29a6fb9af.png)

So, 2 questions:
Why random generator works so strange in this case?
Does quick_random work as per documentation http://graphwalker.github.io/generators_and_stop_conditions/#quickrandom-some-stop-conditions- and really may choose a blocked by a guard edge?

Should say that I like how quick_random works in this case, just interested may documentation should be updated?

[LoginWithIterations.zip](https://github.com/GraphWalker/graphwalker-project/files/628915/LoginWithIterations.zip)

**Comment by KristianKarl** [comment]
Quick random does not work as expected in models with guards. 
In the doc, it says, in step 1 _Choose an edge not yet visited by random_, and the generate the shortest path to it, will not work, if there's a guard blocking that path.

**Comment by nbdnnm** [comment]
@KristianKarl I don't understand what you have answered in the second sentence. I suppose you have mixed few sentences in it.
Could you elaborate a little bit please?

And what with the random behavior, is it correct to choose 15 000 times the same edge LogOut?

**Comment by KristianKarl** [comment]
Quick random assumes that all edges are accessible at all time. If they are not, quick random will not work.
Accessible in this case means that they are not closed by any existing guards.

**Comment by nilols** [comment]
I guess that this question is a bit stale, I'll close this issue. If there is a need for further discussions we should do it in the google group
