### ISSUE TITLE
Logical and Alternative conditions don't work if there is more than 2 options

### ISSUE THREAD

**Issue by nbdnnm** [GraphWalker/graphwalker-project#114]
As per documentation there is possibility to combine stop conditions by and, or expressions.
And nothing mentioned that the number of expressions is limited.
In reality I see that only 2 combined expressions work

![image](https://cloud.githubusercontent.com/assets/22072588/20862759/0c0b4142-b9b4-11e6-8f8a-012919e597b1.png)

![image](https://cloud.githubusercontent.com/assets/22072588/20862745/a8888f30-b9b3-11e6-91cd-238d208d6b93.png)

But I think I know how to fix it

**Comment by Sally-jarkas** [comment]
It doesn't work for me>
I've got 
Exception in thread "main" java.lang.ClassCastException: org.graphwalker.core.condition.CombinedCondition cannot be cast to org.graphwalker.core.condition.ReachedStopCondition

**Comment by nbdnnm** [comment]
Yes, it's still not fixed as far add i know

**Comment by KristianKarl** [comment]
That's correct. It's still an open bug

**Comment by nilols** [comment]
I tried this with unit tests in the core module, using three combined or alternative stop conditions and what I could see this should work or have I missed something?

**Comment by nilols** [comment]
The problem is in the DSL module

**Comment by KristianKarl** [comment]
Let me create a unit test that and see if I can re-create the bug.
I'll add a patch here during the day,

**Comment by KristianKarl** [comment]
I missed that the issue is fixed.
Disregard my comment above
