### ISSUE TITLE
Exception when using value = "AStarPath(ReachedVertex(v_FindOwners))" in GW class annotation

### ISSUE THREAD

**Issue by nbdnnm** [GraphWalker/graphwalker-project#117]
As from https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/graphwalker-3/MkIDGH4tvJM

"For a specific purpose i need to set the 'value' attribute of the GraphWalker annotation to the equivalent of :
   myContext.setPathGenerator(new AStarPath(new ReachedVertex("v_Browse")));
that is
   @GraphWalker(value = "AStartPath(ReachedVertex(v_Browse))"...

Notice that in that problem, I don't use the format a_star(reached_vertex(v_browse))

Unfortunately this raises an exception. My unsertanding is that the GeneratorLoader.exitGenerator(...) method contains a typo.
         ctx.getChild(0).getText().equalsIgnoreCase("astar**t**path")) {

We should have rather
       ctx.getChild(0).getText().equalsIgnoreCase("astarpath")) {"

**Comment by KristianKarl** [comment]
That looks like a typo indeed!

**Comment by KristianKarl** [comment]
Fixed by f9d2082
