### ISSUE TITLE
Swedish characters åäö

### ISSUE THREAD

**Issue by helmfridsson** [GraphWalker/graphwalker-project#13]
![graphwalkerdebuglog](https://cloud.githubusercontent.com/assets/10531123/6690260/d3213892-ccbf-11e4-9249-ba0e35187602.JPG)

![browser](https://cloud.githubusercontent.com/assets/10531123/6690261/d323828c-ccbf-11e4-9f95-1dd415fcb205.JPG)

![model](https://cloud.githubusercontent.com/assets/10531123/6690280/00cb1fb0-ccc0-11e4-8c02-19b7328f2254.JPG)

**Comment by KristianKarl** [comment]
The getData request is fixed by 814368f780e441f9f7f04c801715eaecee1eca14

That output to the console I think is environment dependent. I got correct output on my terminal.

**Comment by KristianKarl** [comment]
Uploaded "latest dev standalone CLI - 3.3.0-SNAPSHOT" on http://graphwalker.org/download
