### ISSUE TITLE
Failure when parsing GeneratorFactory.parse("randompath(length(80))") 

### ISSUE THREAD

**Issue by gw4e** [GraphWalker/graphwalker-project#140]
Hi

The following parsing fails and it should not since length (integer) is a documented stop condition .
GeneratorFactory.parse("randompath(length(80))")

Adding the following test in GeneratorFactoryTest.java exhibit the problem :

  @Test
  public void randompath_length_coverage() {
    PathGenerator generator = GeneratorFactory.parse("randompath(length(80))");
    Assert.assertThat(generator, instanceOf(RandomPath.class));
    Assert.assertThat(generator.getStopCondition(), instanceOf(Length.class));
    Assert.assertThat(((Length) generator.getStopCondition()).getLength(), is(80l));
  }

Regards.

**Comment by nilols** [comment]
Looks like the class [GeneratorLoader](https://github.com/GraphWalker/graphwalker-project/blob/master/graphwalker-dsl/src/main/java/org/graphwalker/dsl/antlr/generator/GeneratorLoader.java), that is used by the GeneratorFactory, doesn't support the Length condition. I guess that this was missed when the GeneratorLoader was implemented.

**Comment by gw4e** [comment]
I created  a pull request.

**Comment by KristianKarl** [comment]
Fixed by PR #141
