### ISSUE TITLE
Moving some tests to the maven verify buildlifecycle 

### ISSUE THREAD

**Issue by KristianKarl** [GraphWalker/graphwalker-project#16]
We have some tests, that arguably could be moved out of the maven test build lifecycle.

The unit tests should be fast. We have some tests that takes seconds to run, rather than milliseconds.
I have a suggestion, that we move those specific tests to a different build lifecycle, "mvn verify".

This would allow us to have and create longer running tests, but still have fast unit tests.

@nilols are you ok that I move those slow tests into the verify cycle? On the Travis CI side, the the verify cycle would be mandatory for a build to pass.

**Comment by nilols** [comment]
sure, we can also enable parallel test execution

**Comment by KristianKarl** [comment]
Parellel is fine
