### ISSUE TITLE
org.graphwalker.core.model.Model (Model model) fails to copy passed model properties

### ISSUE THREAD

**Issue by gw4e** [GraphWalker/graphwalker-project#180]
HI
The public constructor `public  Model(RuntimeModel model) `fails to copy the passed model properties.

We should have something like :
` public Model(RuntimeModel model) {
    **_setProperties(model.getProperties());_**`
...

Regards.

**Comment by KristianKarl** [comment]
I'll look into that today.

**Comment by nilols** [comment]
I have already started looking into this =)

**Comment by nilols** [comment]
@gw4e PR181 is merged, can you verify that it works on your side as expected and then close this issue

**Comment by gw4e** [comment]
Will do.

**Comment by gw4e** [comment]
Model's properties are now available in an "@AfterExecution" method when subclassing ExecutionContext. It works fine.
Good job 🥇
