### ISSUE TITLE
Can't use ReachedEdge & ReachedVertex when using TestBuilder

### ISSUE THREAD

**Issue by scophotog** [GraphWalker/graphwalker-project#182]
I'm using MultipleModelTest.java as inspiration. I can get the EdgeCoverage and VertexCoverage to work fine.

However in the case of ReachedEdge or ReachedVertex, when using the following builder line:

`new TestBuilder().addContext(at.setPathGenerator(new RandomPath(new ReachedVertex("v_confirmScreen"))), MODEL_PATH);`

ReachedVertex.validate will throw a NPE because context.getModel() is null. Is there a way the model can be passed in so validate succeeds?

**Comment by nilols** [comment]
Are you using the latest snapshot version?

**Comment by scophotog** [comment]
I originally tried with v3.4.2 and couldn't get it to work. I then got the source and built all the modules.

**Comment by nilols** [comment]
The problem is that when setting a reached stop condition, GW will validate that the specified end state exists, this fails with a NPE when the context doesn't know about the model yet, using the TestBuilder.

As a workaround until this is fixed you can set the model on the context like this
```java
    new TestBuilder().addContext(at
      .setModel(ContextFactoryScanner.get(MODEL_PATH).create(MODEL_PATH).get(0).getModel())
      .setPathGenerator(new RandomPath(new ReachedVertex("v_confirmScreen"))), MODEL_PATH);
```

**Comment by scophotog** [comment]
Thanks for the work around!

**Comment by nilols** [comment]
Another workaround is to set the path generator after the model is loaded like this
```java
  @Test
  public void reachedCondition() throws IOException {
    MultipleModel_1 model_1 = new MultipleModel_1();
    MultipleModel_2 model_2 = new MultipleModel_2();
    TestBuilder builder = new TestBuilder()
      .addContext(model_1, MODEL_PATH_1)
      .addContext(model_2, MODEL_PATH_2);
    model_1.setPathGenerator(new AStarPath(new ReachedVertex("B")));
    model_2.setPathGenerator(new AStarPath(new ReachedVertex("D")));
    builder.execute();
    assertTrue(model_1.count >= 2);
    assertTrue(model_2.count >= 1);
  }
```

**Comment by nilols** [comment]
After https://github.com/GraphWalker/graphwalker-project/pull/183 is merged you should be able to use
```java
new TestBuilder()
  .addContext(at, MODEL_PATH, new RandomPath(new ReachedVertex("v_confirmScreen")));
```
or
```java
new TestBuilder().addContext(at, MODEL_PATH, "random(reached_vertex(v_confirmScreen))");
```

**Comment by nilols** [comment]
@scophotog PR https://github.com/GraphWalker/graphwalker-project/pull/183 is merged, can you verify that the new approach works for you and then close this issue

**Comment by scophotog** [comment]
Will try, thanks!

**Comment by scophotog** [comment]
I've confirmed both solutions work for me. Thanks for the quick fix!
