### ISSUE TITLE
quick_random generator does not select unvisited edge

### ISSUE THREAD

**Issue by Charrey** [GraphWalker/graphwalker-project#186]
When changing the model and generator of the "boilerplate project" example such that an edge is guaranteed to be unreachable and a "quick_random" strategy is used, we expect the following according to the semantics of quick_random:

- The only unvisited edge will be selected
- Dijkstra will be used to generate a path to that edge
- Dijkstra will fail
- An error occurs

The actual behaviour shows that the only available edge (a self-loop) is selected repeatedly, even though is already visited.

`@GraphWalker(value = "quick_random(edge_coverage(100))", start = "e_FirstAction")`

![smalltest](https://user-images.githubusercontent.com/9192287/37349087-ead40492-26d5-11e8-9af8-8ccad2447506.png)

**Comment by KristianKarl** [comment]
Yes, that is what happens. There is no _kill switch_ in graphwalker, that would assess the situation, like fail if Dijkstra fails. 
The only assessment that is made, is evaluating the stop condition. When it is 100% edge coverage like in this case, that is what is governing graphwalker.

So, certain model designs in combination with generators using different stop conditions, can have [unexpected] effects, that the tester must consider.

**Comment by Charrey** [comment]
Wouldn't that be an interesting addition to Graphwalker?

If it is evident that the stop condition is unachievable, I think the tester would benefit from knowing this (even if it only were a warning).

**Comment by KristianKarl** [comment]
It depends. If the model is a shared model, you can have the situation (using your model as an example):
1) The model exits the vertex **v_VerifySomeAction** (Given that it's SHARED).
2) Enters again at **v_Choice1** (Given that it's SHARED).
We want don't want the execution in the model to fail, because we will re-enter the model many times.

**Comment by nilols** [comment]
It's possible for everyone to create a custom StopCondition in their project, which can stop the execution in the way that suits them, and if your stop condition would benefit others, a PR is always welcome =)

Keep in mind that if you use your own implementation, you have to define the graphwalker annotation like this. 
```java
@GraphWalker(
        pathGenerator = QuickRandomPath.class, 
        stopCondition = EdgeCoverageWithKillSwitch.class, 
        stopConditionValue = "100", 
        start = "e_FirstAction"
)
```

Implementation of EdgeCoverageWithKillSwitch could be something like this
```java
public class EdgeCoverageWithKillSwitch extends EdgeCoverage {

    public EdgeCoverageWithKillSwitch(int percent) {
        super(percent);
    }

    @Override
    public boolean isFulfilled() {
        // if (shouldStopExecutionDueToSomething) {
        //   throw new KillSwitchException(...)
        // }
        return super.isFulfilled();
    }
}
```
