### ISSUE TITLE
Similar project knowledge sharing

### ISSUE THREAD

**Issue by schipiga** [GraphWalker/graphwalker-project#189]
Hey guys!

I looked your project and it looks very interesting. I developed similar one https://github.com/glacejs/glace-testgen, which is used as plugin for framework https://github.com/glacejs/glace-js. And this is article with its work example: https://medium.com/@chipiga86/integration-tests-generating-production-usage-b9050c71bbe3.
Maybe you will be interested in. Will be glad to collaborate.

Regards Sergei

**Comment by KristianKarl** [comment]
Hi Sergei,
Thanks for sharing! Did you have any specific ideas in mind?
What have you tried so far, in terms of perhaps integration the 2 projects?
Best Kristian
