### ISSUE TITLE
Null pointer exception when building a model read from json

### ISSUE THREAD

**Issue by KristianKarl** [GraphWalker/graphwalker-project#19]
A null pointer exception is generated when building a model read from json, using GSON.

Attached patch will generate the problem. 

My guess is that new vertices are created from the source and target vertices in edges. They are 'duplicated', and thus do not match the vertices in the vertex list kept by the model.

[patch.txt](https://github.com/GraphWalker/graphwalker-project/files/14132/patch.txt)

**Comment by KristianKarl** [comment]
The provide patch is an awkward solution to the problem. Or, it at least explains where the problem lies.

I guess, a better solution could be to provide a custom json factory in IO instead. 

[patch.txt](https://github.com/GraphWalker/graphwalker-project/files/14138/patch.txt)

**Comment by nilols** [comment]
Yes, if it's not a bug in core we should solve it outside core. I can have a look at it

**Comment by nilols** [comment]
Can you verify that this is still a issue with the latest master?

**Comment by KristianKarl** [comment]
It's ok now
