### ISSUE TITLE
BinTray: Files can only be published within 180 days from the version publish date.

### ISSUE THREAD

**Issue by KristianKarl** [GraphWalker/graphwalker-project#197]
Bintray does not really support nightly builds, or multiple SNAPHOT releases within the same version more than X number of days.

That's why we don't have the latest dev release available from bintray right now.

See also: https://github.com/LibrePCB/LibrePCB/issues/179

**Comment by toredal** [comment]
Maybe this is a working solution: https://github.com/probonopd/uploadtool
I'll look into that
