### ISSUE TITLE
File names too long for Windows

### ISSUE THREAD

**Issue by klemensschindler** [GraphWalker/graphwalker-project#20]
Checking out the repository from the drive root:
```bash
c:
cd \
git clone https://github.com/GraphWalker/graphwalker-project.git
```

results in an error because a file name is too long for Windows:
```
fatal: cannot create directory at 'graphwalker-studio/src/main/webapp/scripts/tags/node_modules/riot/node_modules/chokidar/node_modules/anymatch/node_modules/micromatch/node_modules/braces/node_modules/expand-range/node_modules/fill-range/node_modules/is-number': Filename too long
```

This problem occurs on a Windows 8 system.

**Comment by nilols** [comment]
Seems to be a windows limitation issue. But tags is not used and after we clean up the studio module this issue should be fixed.

**Comment by nilols** [comment]
I've cleaned up the studio project, please pull the change and try rebuild

**Comment by klemensschindler** [comment]
A fresh clone now builds in windows. The issue is resolved, thanks!
