### ISSUE TITLE
graphwalker check - cul-de-sacs error on vertex with shared_state

### ISSUE THREAD

**Issue by dorinoltean** [GraphWalker/graphwalker-project#204]
I have the [following model ](https://gist.github.com/dorinoltean/3671365268195786781e64869a9a634c)
![model.json](https://i.imgur.com/Q0hQliR.png)
Running 
`gw check -m model.json "random(edge_coverage(100))"`
gives the following error:
> The model has one cul-de-sacs, and is requested to run using a random path generator and 100% edge coverage. That might not work.

Running
`gw offline -m model.json "random(edge_coverage(100))"`
Generates a valid path.

I'm using Latest development standalone CLI - 4.0.0-SNAPSHOT downloaded today

This is caused because shared_state is not taken into consideration during check. Check command counts vertices with 0 out edges but fails to consider that Graphwalker can pass a vertex with a shared state and zero out edges.

**Comment by toredal** [comment]
That is true. The model checker does not take into account that a model can be part of a multi-model run.
Let me check to see if there's an easy way to deal with that.

**Comment by toredal** [comment]
Suggested fix #205
