### ISSUE TITLE
If an action script contains more than 1 semicolon, execution fails

### ISSUE THREAD

**Issue by KristianKarl** [GraphWalker/graphwalker-project#22]
Patch https://github.com/GraphWalker/graphwalker-patch-repo/blob/master/semiColonBug.patch reproduces the problem

**Comment by nilols** [comment]
This is not a issue, you try to execute multiple actions in one Action object, I can't see the purpose of that..

**Comment by KristianKarl** [comment]
Well, if you try to define a function i yed, it wont parse.. 

Either we say that that is not allowed, only simple statements are, or we need to make it javascript compatible all through.

But, this is really only a yed parsing problem. The new webeditor in graphwalker-studio should need to have the restriction.

But we might re-visit the definition of what an action is?

**Comment by nilols** [comment]
Then the problem is in parsing the yEd file, not a issue with graphwalker-core, the test you added in core doesn't make sense, because you group multiple actions into one action. This is more of a feature request and should be handled in the yEd parser.

**Comment by KristianKarl** [comment]
Nah, the test in core I forgot to remove when trouble shooting.

I think we should tackle this by perhaps redefine actions. 
Are they individual statements? Or should it be possible to have pure javascript in the model?
What's the pros and cons?

**Comment by nilols** [comment]
The core module, already support pure javascript and I see no cons with that. This added functionality only affect the parsing of a yEd model and the only change we need to do is in the antlr definitions in the dsl module.

**Comment by KristianKarl** [comment]
The bug is on the yed parser.

**Comment by nilols** [comment]
The parser is generated from the antlr definition, so the change needed for this **enhancement** is in the dsl module.

**Comment by KristianKarl** [comment]
Yeah, thats right. And it's gonna be solved by graphwalker-studio anyways.
