### ISSUE TITLE
if the edge has the same name , how do you give the edgeId value  and how i know which edge is not covered，and which edge is covered, when their name is same.

### ISSUE THREAD

**Issue by JICJ** [GraphWalker/graphwalker-project#227]

**Comment by JICJ** [comment]
![image](https://user-images.githubusercontent.com/22855917/75149021-fb5bb600-573b-11ea-8275-77797a5b3b8d.png)

**Comment by KristianKarl** [comment]
The `edgeId` uniquely identifies an edge.
There can be no duplicated `edgeId`.

You edit the `edgeId` in the `json` file, or in GraphWalker Studio. see [Create a model in Studio](http://graphwalker.github.io/#documentation)

For general questions (not bugs), the forum is perhaps a better place :-)
https://groups.google.com/forum/#!forum/graphwalker

**Comment by JICJ** [comment]
Thank you very much.
