### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by asampaio** [GraphWalker/graphwalker-project#228]
Correct "cretae" at the third bullet of [documentation](http://graphwalker.github.io/#documentation)

**Comment by KristianKarl** [comment]
Thanks!
Fixed

**Comment by asampaio** [comment]
Here [https://github.com/GraphWalker/graphwalker-project/wiki/Offline](url) I  believe the jq command should be outside the double quotes of the generator.
Also, although there is a jq version for windows, the same (output just the names) can be done easily in windows using powershell. Using the same example:
`java -jar graphwalker-cli-4.2.0.jar offline -m Login.graphml "a_star(reached_vertex(v_Browse))" |  ConvertFrom-Json`
Possibly this could also be addeds to the documentation.

**Comment by KristianKarl** [comment]
Yes, indeed. The double-quote was in the wrong place. Thanks!

Regarding an update for PowerShell. You should be able to fork the wiki pages, and post a pull request. That would be very appreciated.
