### ISSUE TITLE
Pet clinic example maven build fail

### ISSUE THREAD

**Issue by TJNK** [GraphWalker/graphwalker-project#230]
FYI - At graphwalker-project/wiki/petclinic; the cmd: mvn tomcat7:run fails with cannot find symbol (XmlElement)

**Comment by KristianKarl** [comment]
Did you run: `git reset --hard 482eeb1c217789b5d772f5c15c3ab7aa89caf279` before 'mvn tomcat7:run`?

It is working with no problems for me, I tried it yesterday.
What does `mvn -version` give for as output?

**Comment by nraiha** [comment]
Hi I have the same issue. mvn -version gives:

```
Apache Maven 3.6.3 (NON-CANONICAL_2019-11-27T20:26:29Z_root)
Maven home: /opt/maven
Java version: 15.0.2, vendor: N/A, runtime: /usr/lib/jvm/java-15-openjdk
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.95-1-manjaro", arch: "amd64", family: "unix"
```
