### ISSUE TITLE
petclinic example test fails

### ISSUE THREAD

**Issue by yigitsoydan** [GraphWalker/graphwalker-project#231]
[ERROR] Failed to execute goal org.graphwalker:graphwalker-maven-plugin:4.2.0:test (default-cli) on project java-petclinic: Execution default-cli of goal org.graphwalker:graphwalker-maven-plugin:4.2.0:test failed: java.lang.reflect.InvocationTargetException: com\company/FindOwners (wrong name: com/company/FindOwners)

**Comment by KristianKarl** [comment]
Hi,
I tested it and it works for me.

To get help, you need to give more information. Please do that either on [GraphWalker forum](https://groups.google.com/forum/#!forum/graphwalker), or file bug report on the [petclinic repo](https://github.com/GraphWalker/graphwalker-example).

Please have a look here to get better help faster: https://github.com/GraphWalker/graphwalker-project/wiki/Creating-a-minimal-working-example-to-get-help

**Comment by darknite12** [comment]
I am getting the same thing. Did @yigitsoydan , were you able to resolve this issue?

**Comment by KristianKarl** [comment]
@darknite12 could elaborate in which context this problems occurs?
What version of java and java?
What OS version.
How did you run the test? Command line or from an IDE?
