### ISSUE TITLE
How to understand requirements in vertex and edge?

### ISSUE THREAD

**Issue by xiechunhong** [GraphWalker/graphwalker-project#234]
In a vertex or edge, there are shared name, guard, weight, actions, requirements, I can understand: 
1. shared name helps current model to link to another model
2. guard like the entry criteria, if the conditions are not true, model will not enter corresponding edge or vertex
3. weight is the possibility considered by path generator when selecting next step
4. actions are actions that executed by edge or vertex when entered
5. requirements? I don't know how to understand it. Does it like precondition, just like the preconditions for a test case? Or does it mean the description of the functionality, just like the product description (also known as requirements).
Could anyone kindly help me understand requirements? Give me some example, or explain what requirements actually do when model executing? Thanks a lot!

**Comment by KristianKarl** [comment]
That's a very good summary indeed.

I understand that we were lacking documentation of the why's regarding requirements. I updated the docs on that part:
https://github.com/GraphWalker/graphwalker-project/wiki/Requirements

Does that clear things up?

**Comment by xiechunhong** [comment]
Thank you Kristian! "requirements" is clear to me now👍

**Comment by KristianKarl** [comment]
Thanks for your feedback!
