### ISSUE TITLE
removing weight on studio mess up the model

### ISSUE THREAD

**Issue by shahafmarom** [GraphWalker/graphwalker-project#241]
when inserting weight to an edge in a model and then removing it using the studio, causes a weight with an empty string which considered an invalid model (fails in checking the model via cmd or trying to play the model in the studio).

**Comment by KristianKarl** [comment]
Thanks for the report.
I'll look into it.

**Comment by KristianKarl** [comment]
Proposed fix PR #242

**Comment by KristianKarl** [comment]
Fixed in master branch
