### ISSUE TITLE
Version upgrade

### ISSUE THREAD

**Issue by titanLuLi** [GraphWalker/graphwalker-project#251]
Now I am trying to upgrade the version to 4.3.0.  It seems some old version functions were gone.
    
ContextFactory factory = ContextFactoryScanner.get(modelPath);
        executionContext = factory.**create**(modelPath, requestModel);
        executionContext.**getScriptEngine**()
Which functions should I use ?

**Comment by KristianKarl** [comment]
The `ContextFactoryScanner.get` return a list of `Context`.
```
ContextFactory factory = ContextFactoryScanner.get(path);
List<Context> contexts = factory.create(path);
```
Also, a `ContextFactory.create` returns a list of `Context`.
