### ISSUE TITLE
there is a trouble in windows system when user pass the path of json file

### ISSUE THREAD

**Issue by yangislet** [GraphWalker/graphwalker-project#253]
The "configureContext" function in the path of graphwalker-java\4.3.0\graphwalker-java-4.3.0.jar!\org\graphwalker\java\test\TestExecutor.class   is not ok.This function replace the path of file,however it only support Mas OS with "/". I suggest that you should auto identify os system. Thanks!

`Class.forName(path.getParent().toString().replace('/', '.') + "." + examineContext.getModel().getName()).isAssignableFrom(context.getClass())`

**Comment by yangislet** [comment]
This tool crazy me ! i can't star

**Comment by KristianKarl** [comment]
Fixed by PR #257

**Comment by KristianKarl** [comment]
Good catch!
Thanks for you report.
