### ISSUE TITLE
is it possible to access coverage information?

### ISSUE THREAD

**Issue by OleksandrKucherenko** [GraphWalker/graphwalker-project#33]
Is it possible during the execution access the coverage metrics?! Will be great to publish that in logs during the execution.

**Comment by nilols** [comment]
Short answer yes, 
Every test is executed in a ExecutionContext, the context have a reference to a profiler and the profiler can tell you e.g. what's left to visit, so you should be able to get the information you want. Another solution is to create your own observer and attach it to the machine, depending a bit on how you execute the tests.
