### ISSUE TITLE
Is it possible to low chances of edge/vertex for being selected next in graph?!

### ISSUE THREAD

**Issue by OleksandrKucherenko** [GraphWalker/graphwalker-project#35]
I have a graph in which specific route should be executed only on the last loop/cycle. Is it possible to hint graphwalker to point that specific edge/vertex should stay last in list of possible selections for next step, especially if in graph still exists untouched edges or vertexes.

**Comment by nilols** [comment]
yes, but at the moment it put some restrictions to the model, we're currently missing the eulerization part, this means that you must ensure that a euler path already exits in your model and then run your test with the ShortestAllPaths generator. Btw questions should really be handled in the google group https://groups.google.com/forum/#!forum/graphwalker-3
