### ISSUE TITLE
Simplify model creation for tests

### ISSUE THREAD

**Issue by maikeru** [GraphWalker/graphwalker-project#52]
It might be nice if we modified the Model class so that we could easily build variations on a common model for testing purposes. i.e. something like this:

``` java
Model baseModel = new Model()
     .addEdge(edge1)

Model firstVariant = baseModel.but().withEdge(edge2); // model with edges 1 and 2
Model secondVariant = baseModel.but().withEdge(edge3); // model with edges 1 and 3
```

The method naming doesn't have to be like this, it's just what I'm familiar with. Let's discuss and then I could potentially make a separate pull request for that.

By the way, the idea for this comes from  [this blog post](http://www.natpryce.com/articles/000724.html).

**Comment by nilols** [comment]
We sort of have this already, with ```new Model(baseModel)``` we can create a new instance of a base model that we can modify to suite our test

**Comment by maikeru** [comment]
Looks good to me. Let's close this for now.
