### ISSUE TITLE
java: TestBuilder::execute returns null

### ISSUE THREAD

**Issue by KristianKarl** [GraphWalker/graphwalker-project#6]
The TestBuilder::execute always returns nullsince it's hard coded:  https://github.com/GraphWalker/graphwalker-project/blob/master/graphwalker-java/src/main/java/org/graphwalker/java/test/TestBuilder.java#L84

The example on http://graphwalker.org/docs/workflow needs this method to work.

**Comment by nilols** [comment]
This issue should be fixed now in master, the solution was to add support of executing a context directly with the TestExecutor, used by the TestBuilder.
